sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true react-test npm test

after_success:
  - docker build -t wujenny15/multi-client ./client
  - docker build -t wujenny15/multi-nginx ./nginx
  - docker build -t wujenny15/multi-server ./server
  - docker build -t wujenny15/multi-worker ./worker
  # Log into the docker cli
  - echo "DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Tells the docker to get the password from the stdin
  # Take these images and push them to docker hub
  - docker push wujenny15/multi-client
  - docker push wujenny15/multi-nginx
  - docker push wujenny15/multi-server
  - docker push wujenny15/multi-worker
